### ISSUE TITLE
Syntax Error in setup.py

### ISSUE THREAD

**Issue by Seriousness** [Rudd-O/ledgerhelpers#12]
when doing `sudo python setup.py install` as suggested by the manual it ends with:

```
 File "setup.py", line 16
    raise ValueError, '"__version__" not found in "src/ledgerhelpers/__init__.py"'
                    ^
SyntaxError: invalid syntax
```

**Comment by Rudd-O** [comment]
I've ported the code (it's a `2to3` port) to Python 3.  I cannot make any guarantees that the program will work as required, but you should try it nonetheless.  Latest `master` as well as tag `v0.3.0` contain the new code.
