### ISSUE TITLE
Add an "Installation / usage" section to readme

### ISSUE THREAD

**Issue by gavinhughes** [Rudd-O/ledgerhelpers#2]
An "Installation / usage" section in readme would be helpful for non-python users.

**Comment by alexjj** [comment]
I agree that would be useful, but to get anyone started:

```
git clone https://github.com/Rudd-O/ledgerhelpers.git
cd ledgerhelpers
sudo python setup.py install
```

Then everything under [bin](https://github.com/Rudd-O/ledgerhelpers/tree/master/bin) will be commands you can run from the terminal.

_Other install methods are possible too._

**Comment by Rudd-O** [comment]
I have pushed a fix or this.
