### ISSUE TITLE
Execution fails on Arch Linux (env python problem)

### ISSUE THREAD

**Issue by buckket** [Rudd-O/ledgerhelpers#6]
Hi, throughout the code `env python` is used in the shebang to load the appropriate Python interpreter. On Distributions where `python` defaults to Python 3 (e.g. Arch Linux) running the code will fail, as it is Python 2 only.

I suggest being explicit about the Python 2 dependence, thus changing `#!/usr/bin/env python` to `#!/usr/bin/env python2` everywhere.

This would also allow me to simplify the process of packaging these programs.

**Comment by Rudd-O** [comment]
Good news.  v0.0.30 has solved this problem.
